### ISSUE TITLE
pushing to array crashes watchjs

### ISSUE THREAD

**Issue by utillity** [melanke/Watch.JS#118]
this is my code adding a new entry to state.connections:

```
function Connection(ip, desc) {
	this.ipAddress = ip;
	this.description = desc;
	this.status = "Active";
	this.connectedSince = Date.now();
}

var getOrCreateConnection = function(request) {
	var ip = getClientAddress(request);
	var conn = state.connections.find(e => e.ipAddress == ip);
	if (conn != null)
	{
		if (conn.status != "Active")
		{
			conn.status = "Active";
			conn.connectedSince = Date.now();
			console.log("Connection reestablished with " + ip);
		}
	}
	else
	{
		console.log("Connection established with " + ip);
		conn = new Connection(ip, "Unknown");
		state.connections.push(conn);
	}
	return conn;
}
```

on pushing conn to state.connections, I get the following error:

```
C:\DEV\uTILLIty\DP\MK4\GOP.UI\Server\node_modules\melanke-watchjs\src\watch.js:114
            copy[attr] = obj[attr];
                       ^

TypeError: Cannot set property 'ipAddress' of undefined
    at clone (C:\DEV\uTILLIty\DP\MK4\GOP.UI\Server\node_modules\melanke-watchjs\src\watch.js:114:24)
    at pushToLengthSubjects (C:\DEV\uTILLIty\DP\MK4\GOP.UI\Server\node_modules\melanke-watchjs\src\watch.js:735:22)
    at watchOne (C:\DEV\uTILLIty\DP\MK4\GOP.UI\Server\node_modules\melanke-watchjs\src\watch.js:255:13)
    at watchMany (C:\DEV\uTILLIty\DP\MK4\GOP.UI\Server\node_modules\melanke-watchjs\src\watch.js:235:13)
    at Timeout.loop [as _onTimeout] (C:\DEV\uTILLIty\DP\MK4\GOP.UI\Server\node_modules\melanke-watchjs\src\watch.js:681:29)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by englishextra** [comment]
that's because ```if (conn != null)``` - check staright for null or undefined.  It's up to you.

**Comment by utillity** [comment]
sorry, I don't get it. Chaning code to the following yields same result (error and crash):

```
	if (conn == null)
	{
		console.log("Connection established with " + ip);
		conn = new Connection(ip, "Unknown");
		state.connections.push(conn);
	}
	else
	{
		if (conn.status != "Active")
		{
			conn.status = "Active";
			conn.connectedSince = Date.now();
			console.log("Connection reestablished with " + ip);
		}
	}

```

**Comment by englishextra** [comment]
Cannot comment if I haven't a demo or test repo.

**Comment by utillity** [comment]
ok, found the problem. my class has a ctor with parameters. Had to add another ctor which would also init the properties. Not very nice to have to do that, though.

```
function Connection(ip, desc) {
	this.ipAddress = ip;
	this.description = desc;
	this.status = "Active";
	this.connectedSince = Date.now();
}
Connection.prototype = {
	ipAddress: null,
	description: null,
	status: "Active",
	connectedSince: Date.now()
};

```

**Comment by englishextra** [comment]
```
undefined != null  // false
undefined !== null // true
```

**Comment by englishextra** [comment]
the mistake is here if (conn == null)

**Comment by melanke** [comment]
If I understand it right the problem was solved, I am closing this issue. Reopen if needed.
